### PR TITLE
create lmdb for large dataset

### PR DESCRIPTION
**Pull request by Cugtyt**
create lmdb for large dataset #125 

Code is modified from `create_lmdb.py`, change are:
* datasize is not calculated after loading imgs, but use `os.stat()`. 
* read imgs one by one
* after a batch of `put`s, commit txn, and get it again.

### CODE REVIEW

**Comment by xinntao** [comment]
Hi @Cugtyt 
Thank you very much :+1: 
If possible, could it be added to the original `create_lmdb_dataset.py`? Thus, the codes will be more concise. 

There are two modes: 1) read all images to memory and then write to lmdb, which is faster but consumes more memory; 2) add images one by one, which is suitable for scenarios with less memory. The users can select their preferred mode.

**Comment by Cugtyt** [comment]
Yeah, I added it into create_lmdb.py, there is a variable `mode` (=1 or 2) for small data and large data, I didn't use `argparse` since users always need to modify the config for their needs.

**Comment by retrontology** [comment]
lmdb large dataset

**Comment by xinntao** [comment]
Thanks :+1:

**Pull request merged**
